name: Package Application with Pyinstaller
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.4
    - run: pip install jsonpath_ng pyinstaller
    - run: pyinstaller -F StreamDeckFolder.py
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
